name: tuotu
version: "1.0"
summary: tuotu
description: A new CrossPlatform FileTransfer Tool!

confinement: strict
base: core22
grade: stable
 
apps:
  tuotu:
    command: tuotu
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      nmcli: network-manager
      - desktop
      - network
    #- network-manager
    #- fuse-support
      - home
    slots:
      - dbus-tuotu

#plugs:
  #network-manager:
    #interface: network-manager
    #auto-connection: true


slots:
  service: network-manager
  dbus-tuotu: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.digitalevers.tuotu # adjust accordingly to your app name and
   
parts:
  zenity:
    plugin: nil
    stage-packages:
      - zenity
  tuotu:
    after:
      - zenity
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
