name: tuotu
version: "1.0"
summary: tuotu
description: A new CrossPlatform FileTransfer Tool!

confinement: strict
base: core22
grade: stable
 
apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  nmtui:
    command: usr/bin/nmtui
    plugs: [nmcli]
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs: [nmcli]
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs: [nmcli]
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs: [nmcli]
  tuotu:
    command: bin/tuotu
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - desktop
      - network
      - home
    slots:
      - service
      - dbus-tuotu

#plugs:
  #network-manager:
    #interface: network-manager
    #auto-connection: true
plugs:
  nmcli: network-manager

slots:
  service: network-manager
  dbus-tuotu: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.digitalevers.tuotu # adjust accordingly to your app name and
   
parts:
  zenity:
    plugin: nil
    stage-packages:
      - zenity
  tuotu:
    after:
      - zenity
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
